trigger:
  - master  # Trigger on changes to the main branch

pool:
  name: agent
 
stages:
  - stage: Build
    displayName: Development
    jobs:
      - job: Build
        displayName: Development
        steps:
          # Create an artifact directory and copy the necessary files
          - powershell: |
              mkdir "$(Build.ArtifactStagingDirectory)\webAppDrop"
              Copy-Item -Path "$(System.DefaultWorkingDirectory)\*.*" -Destination "$(Build.ArtifactStagingDirectory)\webAppDrop" -Recurse -Force
            displayName: Package Web App

          # Publish the artifact
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)\webAppDrop'
              ArtifactName: 'webAppDrop'

  - stage: DevRelease
    displayName: 'ReadyForDevRelease'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: waitForValidation
        displayName: Waiting for approval to promote QA Release
        pool: server
        timeoutInMinutes: 4320  # job times out in 3 days
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 1400  # task times out in 1 day
            inputs:
              notifyUsers: | 
                sathishksuresh@gmail.com
              instructions: 'Waiting for approval to promote QA Release'
              onTimeout: 'resume'

  - stage: DeployDev
    displayName: Deploy dev to IIS 
    dependsOn: DevRelease
    condition: succeeded()
    jobs:
      - deployment: DevDeployment
        displayName: 'Deploy to Dev'
        environment: 'Dev'
        strategy:
          runOnce:
            deploy:
              steps:
                # Download the artifact
                - task: DownloadBuildArtifacts@0
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: 'webAppDrop'
                    downloadPath: '$(Pipeline.Workspace)\webAppDrop'

                # Deploy to IIS dev folder
                - powershell: |
                    $SourcePath = "$(Pipeline.Workspace)\webAppDrop"
                    $DestPath = "C:\inetpub\wwwroot\dev"

                    Write-Host "Source Path: $SourcePath"
                    Write-Host "Destination Path: $DestPath"

                    if (-Not (Test-Path $DestPath)) {
                        New-Item -ItemType Directory -Force -Path $DestPath
                    }

                    if (Test-Path $SourcePath) {
                        Copy-Item -Path "$SourcePath\*" -Destination $DestPath -Recurse -Force
                        Write-Host "Web app deployed successfully to dev."
                    } else {
                        Write-Host "ERROR: Source path does not exist."
                        exit 1
                    }
                  displayName: Deploy Web App to IIS (Dev)

                # Restart IIS to apply changes
                - powershell: |
                    Write-Host "Restarting IIS..."
                    iisreset
                  displayName: Restart IIS (Dev)

  - stage: QARelease
    displayName: 'ReadyForQARelease'
    dependsOn: DeployDev
    condition: succeeded()
    jobs:
      - job: waitForValidation
        displayName: Waiting for approval to promote QA Release
        pool: server
        timeoutInMinutes: 4320  # job times out in 3 days
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 1400  # task times out in 1 day
            inputs:
              notifyUsers: |
                sathishksuresh@gmail.com
              instructions: 'Waiting for approval to promote QA Release'
              onTimeout: 'resume'

  - stage: DeployQA
    displayName: Deploy QA to IIS 
    dependsOn: QARelease
    condition: succeeded()
    jobs:
      - deployment: QADeployment
        displayName: 'Deploy to QA'
        environment: 'QA'
        strategy:
          runOnce:
            deploy:
              steps:
                # Download the artifact
                - task: DownloadBuildArtifacts@0
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: 'webAppDrop'
                    downloadPath: '$(Pipeline.Workspace)\webAppDrop'

                # Deploy to IIS QA folder
                - powershell: |
                    $SourcePath = "$(Pipeline.Workspace)\webAppDrop"
                    $DestPath = "C:\inetpub\wwwroot\qa"

                    Write-Host "Source Path: $SourcePath"
                    Write-Host "Destination Path: $DestPath"

                    if (-Not (Test-Path $DestPath)) {
                        New-Item -ItemType Directory -Force -Path $DestPath
                    }

                    if (Test-Path $SourcePath) {
                        Copy-Item -Path "$SourcePath\*" -Destination $DestPath -Recurse -Force
                        Write-Host "Web app deployed successfully to QA."
                    } else {
                        Write-Host "ERROR: Source path does not exist."
                        exit 1
                    }
                  displayName: Deploy Web App to IIS (QA)

                # Restart IIS to apply changes
                - powershell: |
                    Write-Host "Restarting IIS..."
                    iisreset
                  displayName: Restart IIS (QA)

  - stage: DeployProduction
    displayName: Deploy Prod to IIS 
    dependsOn: QARelease  # Make sure this depends on the QARelease stage
    condition: succeeded()
    jobs:
      - deployment: ProductionDeployment
        displayName: 'Deploy to Prod'
        environment: 'Production'
        strategy:
          runOnce:
            deploy:
              steps:
                # Download the artifact (published app)
                - task: DownloadBuildArtifacts@0
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: 'webAppDrop'
                    downloadPath: '$(Pipeline.Workspace)\webAppDrop'

                # Deploy to IIS production folder
                - powershell: |
                    $SourcePath = "$(Pipeline.Workspace)\webAppDrop"
                    $DestPath = "C:\inetpub\wwwroot\production"

                    Write-Host "Source Path: $SourcePath"
                    Write-Host "Destination Path: $DestPath"

                    if (-Not (Test-Path $DestPath)) {
                        New-Item -ItemType Directory -Force -Path $DestPath
                    }

                    if (Test-Path $SourcePath) {
                        Copy-Item -Path "$SourcePath\*" -Destination $DestPath -Recurse -Force
                        Write-Host "Web app deployed successfully to production."
                    } else {
                        Write-Host "ERROR: Source path does not exist."
                        exit 1
                    }
                  displayName: Deploy Web App to IIS (Production)

                # Restart IIS to apply changes
                - powershell: |
                    Write-Host "Restarting IIS..."
                    iisreset
                  displayName: Restart IIS (Production)
