trigger:
- none

pool:
  name: agent

stages:
- stage: Build
  displayName: Build 
  condition: and(succeeded(), or(startsWith(variables['Build.SourceBranch'], 'refs/heads/release'), eq(variables['Build.SourceBranch'], 'refs/heads/development'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix')))
  jobs:
    - job: Build
      displayName: Build
      steps:
        - script: |
            echo $(Build.SourceBranch)
          displayName: 'Debug Build.SourceBranch'
        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '6.x'
            installationPath: $(Agent.ToolsDirectory)/dotnet

        - script: |
            dotnet restore $(Build.SourcesDirectory)/Website-Demo.csproj
            dotnet publish $(Build.SourcesDirectory)/Website-Demo.csproj -c Release -o $(Build.ArtifactStagingDirectory)\publish
          displayName: 'Restore and Build the Project'

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)\publish'
            ArtifactName: 'webAppDrop'

- stage: DevRelease
  displayName: 'ReadyForDevRelease'
  dependsOn: Build
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/hotfix'))  # Skip this stage for hotfix
  jobs:
    - job: waitForValidation
      displayName: Waiting for approval to promote QA Release
      pool: server
      timeoutInMinutes: 4320
      steps:
        - task: ManualValidation@0
          timeoutInMinutes: 1400
          inputs:
            notifyUsers: |
              sathishksuresh@gmail.com
            instructions: 'Waiting for approval to promote QA Release'
            onTimeout: 'resume'

- stage: DeployDev
  displayName: Deploy dev to IIS
  dependsOn: DevRelease
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/hotfix'))  # Skip this stage for hotfix
  jobs:
    - deployment: DevDeployment
      displayName: 'Deploy to Dev'
      environment: 'Dev'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadBuildArtifacts@0
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'webAppDrop'
                  downloadPath: '$(Pipeline.Workspace)\webAppDrop'
              - powershell: |
                  Write-Host "Build.SourceBranch is: $(Build.SourceBranch)"
                displayName: Debug Build.SourceBranch
              - powershell: |
                  iisreset /stop
                displayName: Stop IIS (Dev)
              - powershell: |
                  $SourcePath = "$(Pipeline.Workspace)\webAppDrop"
                  $DestPath = "C:\inetpub\wwwroot\dev"

                  if (-Not (Test-Path $DestPath)) {
                    New-Item -ItemType Directory -Force -Path $DestPath
                  }

                  if (Test-Path $SourcePath) {
                    Copy-Item -Path "$SourcePath\*" -Destination $DestPath -Recurse -Force
                  } else {
                    exit 1
                  }
                displayName: Deploy Web App to IIS (Dev)

              - powershell: |
                  iisreset /start
                displayName: Start IIS (Dev)

- stage: QARelease
  displayName: 'ReadyForQARelease'
  dependsOn: DeployDev
  condition: or(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix'))  # Runs for hotfix as well
  jobs:
    - job: waitForValidation
      displayName: Waiting for approval to promote QA Release
      pool: server
      timeoutInMinutes: 4320
      steps:
        - task: ManualValidation@0
          timeoutInMinutes: 1400
          inputs:
            notifyUsers: |
              sathishksuresh@gmail.com
            instructions: 'Waiting for approval to promote QA Release'
            onTimeout: 'resume'

- stage: DeployQA
  displayName: Deploy QA to IIS
  dependsOn: QARelease
  condition: or(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix'))  # Runs for hotfix as well
  jobs:
    - deployment: QADeployment
      displayName: 'Deploy to QA'
      environment: 'QA'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadBuildArtifacts@0
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'webAppDrop'
                  downloadPath: '$(Pipeline.Workspace)\webAppDrop'

              - powershell: |
                  iisreset /stop
                displayName: Stop IIS (QA)

              - powershell: |
                  $SourcePath = "$(Pipeline.Workspace)\webAppDrop"
                  $DestPath = "C:\inetpub\wwwroot\qa"

                  if (-Not (Test-Path $DestPath)) {
                    New-Item -ItemType Directory -Force -Path $DestPath
                  }

                  if (Test-Path $SourcePath) {
                    Copy-Item -Path "$SourcePath\*" -Destination $DestPath -Recurse -Force
                  } else {
                    exit 1
                  }
                displayName: Deploy Web App to IIS (QA)

              - powershell: |
                  iisreset /start
                displayName: Start IIS (QA)

- stage: ProdRelease
  displayName: 'ReadyForProdRelease'
  dependsOn: DeployQA
  condition: or(startsWith(variables['Build.SourceBranch'], 'refs/heads/release'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix'))


  jobs:
    - job: waitForValidation
      displayName: Waiting for approval to promote Prod Release
      pool: server
      timeoutInMinutes: 4320
      steps:
        - task: ManualValidation@0
          timeoutInMinutes: 1400
          inputs:
            notifyUsers: |
              sathishksuresh@gmail.com
            instructions: 'Waiting for approval to promote Prod Release'
            onTimeout: 'resume'

- stage: DeployProduction
  displayName: Deploy Prod to IIS
  dependsOn: ProdRelease
  condition: or(startsWith(variables['Build.SourceBranch'], 'refs/heads/release'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix'))
  jobs:
    - deployment: ProductionDeployment
      displayName: 'Deploy to Prod'
      environment: 'Production'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadBuildArtifacts@0
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'webAppDrop'
                  downloadPath: '$(Pipeline.Workspace)\webAppDrop'
              - powershell: |
                  iisreset /stop
                displayName: Stop IIS (Prod)

              - powershell: |
                  $SourcePath = "$(Pipeline.Workspace)\webAppDrop"
                  $DestPath = "C:\inetpub\wwwroot\production"

                  if (-Not (Test-Path $DestPath)) {
                    New-Item -ItemType Directory -Force -Path $DestPath
                  }

                  if (Test-Path $SourcePath) {
                    Copy-Item -Path "$SourcePath\*" -Destination $DestPath -Recurse -Force
                  } else {
                    exit 1
                  }
                displayName: Deploy Web App to IIS (Production)

              - powershell: |
                  iisreset /start
                displayName: Start IIS (Production)
